# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: lha
version: '0.0.0'
github: "kleidukos/lha"
license: MIT
author: "Kleidukos"
maintainer: "Kleidukos"
# synopsis: A new Haskeleton package.
# description: lha is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wmissing-export-lists
  - -Wpartial-fields

library:
  dependencies:
  - base-noprelude
  - text
  - relude
  - colourista
  - containers
  source-dirs: src

executables:
  lha:
    source-dirs: app
    main: Main.hs
    dependencies:
    - base-noprelude
    - lha
    - relude
    - text
    - containers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  lha-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base-noprelude
    - lha
    - criterion

tests:
  lha-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - lha
    - tasty
    - tasty-hspec
